joinpoint: revised
bcgov/opho-cdr-shiny pull request #47
Opened 2022-07-01 18:08 UTC by mahm00d27

Revised parts of report

2022-07-02 02:54 UTC, shyan0903 commented on docs/report/capstone-report.Rmd
> +are different standardized chronic disease rates, and time in years
```suggestion
are different age-standardized rates, and time in years
```

2022-07-02 03:01 UTC, shyan0903 requested changes, later dismissed

2022-07-02 03:01 UTC, shyan0903 commented on docs/report/capstone-report.Rmd
> +connected at unknown points, segmented are used as regression models.
```suggestion
connected at unknown points, segmented regression models are used.
```

2022-07-02 03:01 UTC, shyan0903 commented on docs/report/capstone-report.Rmd
> +They also termed as or broken-line models. Here the response variable
```suggestion
They also termed as broken-line models. Here the response variable
```

2022-07-02 03:01 UTC, shyan0903 commented on docs/report/capstone-report.Rmd
> +(2001 to 2020) being the explanatory variable. This type of model is
```suggestion
(2001 to 2020) is the explanatory variable. This type of model is
```

2022-07-02 03:01 UTC, shyan0903 commented on docs/report/capstone-report.Rmd
> +particularly applied in the filed of epidemiology, occupational
```suggestion
particularly applied in the fields of epidemiology, occupational
```

2022-07-02 03:01 UTC, shyan0903 commented on docs/report/capstone-report.Rmd
> +medicine, toxicology, and ecology, where often, the goal is to to
```suggestion
medicine, toxicology, and ecology, where often, the goal is to
```

2022-07-03 04:48 UTC, chendaniely approved these changes

2022-07-03 04:51 UTC, merged